Featrue/broadcast
mosn/mosn pull request #1447
Opened 2020-10-29 13:25 UTC by dengqian

### Issues associated with this PR

Your PR should present related issues you want to solve.

### Solutions
Add a new type of stream filter: broadcast, which broadcast the request to the specified cluster configured in per_filter_config.
Config example:
```
 "listeners": [
        {
          "name": "bindListener",
          "address": "0.0.0.0:530",
          "bind_port": true,
          "network": "tcp",
          "stream_filters": [
            {
              "type": "broadcast"
            }
          ],
          "filter_chains": [
            {
              "tls_context": {},
              "filters": [
                {
                  "type": "proxy",
                  "config": {
                    "downstream_protocol": "Http1",
                    "upstream_protocol": "Http1",
                    "router_config_name": "default_router"
                  }
                }
              ]
            }
          ],
...
              "routers": [
                {
                  "match": {
                    "prefix": "/br"
                  },
                  "per_filter_config" : {
                    "broadcast": {
                      "cluster": "testCluster"
                    }
                  }
                }
...
```

2020-11-30 03:03 UTC, nejisama commented on pkg/filter/stream/broadcast/broadcast.go
> +		return api.StreamFilterStop
api.StreamFilterSto只会中止当前phase的stream filter，后续的流程还需要继续走，这个filter 看上去是接管了所有后续的LB和路由流程，这种异常Stop以后 应该会有问题吧

2020-11-30 03:09 UTC, nejisama requested changes

2020-11-30 03:09 UTC, nejisama commented on pkg/types/stream.go
> +	UpdateHost(Host)
connpool 支持UpdateHost 会有一些问题，这里使用这个接口的必要性 有待讨论

2020-11-30 03:09 UTC, nejisama commented on pkg/filter/stream/broadcast/broadcast.go
> +	host            types.Host
没有用的成员 就先删掉吧，遵循golint的提示，后面也有类似的问题

2020-11-30 03:09 UTC, nejisama commented on pkg/filter/stream/broadcast/broadcast.go
> +	for i := 0; i < snap.HostNum(nil); i++ {
看了一下，MOSN 默认的逻辑是一个请求，只LB一次。 这里的需求是一个请求要给Cluster对应的所有HOST都转发，所以使用了UpdateHost来不断的替换connpool里的HOST 而做到这个目的。这个实现太HACK了。

2020-12-21 12:28 UTC, taoyuanyuan commented on pkg/types/context.go
> +	ContextKeyRoundRobinIndex
可以改为变量机制，可以参考 VarProxyGlobalTimeout

2020-12-21 12:29 UTC, taoyuanyuan commented on pkg/types/loadbalancer.go
> +	RequestRoundRobin  LoadBalancerType = "LB_REQUEST_ROUNDROBIN"
这个估计不通用，只能和mirror模块配合使用，可以直接放到mirror的目录下一起

2020-12-21 12:33 UTC, taoyuanyuan commented on pkg/upstream/cluster/loadbalancer.go
> +			log.DefaultLogger.Debugf("[lb] [RequestRoundRobin] choose host: %s", targets[id].AddressString())
加上 loglevel的判断，减少逃逸

2020-12-21 12:34 UTC, taoyuanyuan commented on pkg/upstream/cluster/loadbalancer.go
> +	for i := ind; i < ind + total; i++ {
应该是 i<total ？

2020-12-21 12:36 UTC, taoyuanyuan commented on pkg/filter/stream/mirror/mirror.go
> +		for i := 0; i < amplification; i++ {
需要判断connpool是否为空

2020-12-22 06:15 UTC, taoyuanyuan commented on pkg/proxy/var.go
> +		variable.NewIndexedVariable(types.VarProxyUpstreamIndex, nil, nil, variable.BasicSetter, 0),
定义放到LB模块里面

2020-12-22 06:16 UTC, taoyuanyuan commented on pkg/types/variable.go
> +	VarProxyUpstreamIndex string = "upstream_index"
放到LB模块

2020-12-22 08:52 UTC, nejisama commented on configs/mosn_config_broadcast.json
> +{
这里补一个配置其实没有太多意义，可以参考test/cases下的代码，补一个test cases 比较合适

2020-12-26 03:23 UTC, taoyuanyuan approved these changes
LGTM

2020-12-29 03:23 UTC, champly commented on pkg/filter/stream/mirror/mirror.go
> +		m.receiveHandler.SendHijackReply(200, m.headers)
replace 200 with `types.SuccessCode`

2020-12-29 03:23 UTC, champly commented on pkg/upstream/cluster/loadbalancer.go
> +		id := i % total
如果这里直接取模有可能会导致流量重复发送到健康到节点

2020-12-29 05:12 UTC, champly approved these changes
LGTM

2020-12-29 11:46 UTC, nejisama approved these changes

2020-12-29 11:46 UTC, merged