Feature/trace jaeger
mosn/mosn pull request #1593
Opened 2021-02-20 04:14 UTC by Magiczml

# 概述

为mosn加入jaeger trace的链路追踪功能。

# 项目结构
- mosn
  - pkg
    - trace
      - jaeger

# 启动

二开逻辑：
1、在项目启动时，我们需要把`jaeger`插件注册进mosn的trace driver中。因此在`mosn/pkg/trace/jaeger/driver.go`中注册driver

```go
const (
	JaegerDriverName = "jaeger"
)

func init() {
	trace.RegisterDriver(DriverName, NewJaegerImpl())
}

```

然后需要在mosn的启动文件中引入这个包`mosn/cmd/mosn/main/mosn.go`

```go
import (
    _ "mosn.io/mosn/pkg/trace/jaeger"
)
```

2、把关键数据inject入jaeger的span中

查看`mosn/pkg/trace/jaeger/span.go`文件，如果想要添加额外的数据，则可以修改下面的函数就可以

```go
//SetRequestInfo 把当前请求相关信息放入span中
func (s *Span) SetRequestInfo(reqinfo api.RequestInfo) {
	span := s.jaegerSpan
	span.SetTag("request_size", reqinfo.BytesReceived())
	span.SetTag("response_size", reqinfo.BytesSent())
	if reqinfo.UpstreamHost() != nil {
		span.SetTag("upstream_host_address", reqinfo.UpstreamHost().AddressString())
	}
	if reqinfo.DownstreamLocalAddress() != nil {
		span.SetTag("downstream_host_address", reqinfo.DownstreamRemoteAddress().String())
	}

	code := reqinfo.ResponseCode()
	span.SetTag("http.status_code", code)

	if isErrorResponse(code) {
		span.SetTag("error", true)
		span.SetTag("error.message", http.StatusText(code))
	}
	span.SetTag("mosn_process_time", reqinfo.ProcessTimeDuration().String())
}
```

3、实际使用
然后我们在项目启动的配置文件中配置使用jaeger就可以了。例子如下：

```json
{
    "tracing": {
        "enable": true,                            //是否启动tracing功能
        "driver": "jaeger",                        //driver选择jaeger
        "config": {
            "service_name": "sample_sidecar",      //当前sidecar上报到jaeger的服务名称，建议【应用服务名_sidecar】,不设置则默认值为：default_sidecar
            "agent_host": "127.0.0.1:6831"       //当前jaeger agent的地址，不设置则默认值为：0.0.0.0:6831
        }
    },
}
```

2021-05-14 05:06 UTC, nejisama requested changes

2021-05-14 05:06 UTC, nejisama commented on pkg/trace/jaeger/span.go
> +	traceString := fmt.Sprintf("%s", s.jaegerSpan)
这个看上去应该是调用了jaeger的Span的String方法，建议直接调用，不要用Sprintf的方法

2021-05-14 05:06 UTC, nejisama commented on pkg/trace/jaeger/tracer.go
> +	tracer, _, err := cfg.New(getServiceName(traceCfg))
根据lint表示，这个方法是废弃方法。建议更换

2021-05-14 05:06 UTC, nejisama commented on pkg/trace/jaeger/tracer.go
> +	return "0.0.0.0:6831"
这种hardcode的地址 来源是什么

2021-05-14 05:06 UTC, nejisama commented on pkg/trace/jaeger/tracer.go
> +	ctx = opentracing.ContextWithSpan(ctx, sp)
这里lint显示是无效的赋值

2021-05-14 05:06 UTC, nejisama commented on pkg/trace/jaeger/tracer.go
> +	ctx = opentracing.ContextWithSpan(ctx, sp)
看了下逻辑，确实是无效赋值。这里入参有一个ctx，然后又重新赋值了两个ctx，最终没有使用这个ctx

2021-05-20 08:37 UTC, nejisama commented
暂时从版本计划里排除，请调整以后再合并，多谢 @Magiczml

2021-06-17 10:29 UTC, Magiczml commented on pkg/trace/jaeger/tracer.go
> +	return "0.0.0.0:6831"
:6831 端口是jaeger agent的默认端口，如果在不设置的场景下可以使用默认端口。减少配置项，我重新提取出来放在变量中

2021-06-17 10:29 UTC, Magiczml commented on pkg/trace/jaeger/tracer.go
> +	return "0.0.0.0:6831"
@nejisama

2021-06-17 10:31 UTC, Magiczml commented
@nejisama 感谢你的review，非常的细致。我已经根据你的意见重新调整，已提交代码，辛苦你再次review。

2021-06-29 03:02 UTC, nejisama commented on pkg/trace/jaeger/span.go
> +		span.SetTag("upstream_host_address", reqinfo.UpstreamHost().AddressString())
SetTag 已经修改为不支持了，这里的这些用法，可能会导致信息缺失了，需要再看看

2021-06-29 03:44 UTC, nejisama approved these changes
LGTM

2021-06-29 05:50 UTC, taoyuanyuan commented on pkg/trace/jaeger/driver.go
> +package jaeger
License

2021-06-29 05:52 UTC, taoyuanyuan commented on pkg/trace/jaeger/propagation.go
> +package jaeger
License

2021-06-29 06:01 UTC, taoyuanyuan commented on pkg/trace/jaeger/tracer.go
> +	//defer closer.Close()
delete unused code

2021-06-29 08:44 UTC, taoyuanyuan approved these changes
LGTM

2021-06-29 08:53 UTC, nejisama approved these changes

2021-06-29 08:53 UTC, merged