fix: add build tag to disable dynamic link with libwasmer.so
mosn/mosn pull request #1608
Opened 2021-03-17 09:37 UTC by antJack

### Issues associated with this PR

Your PR should present related issues you want to solve.

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

2021-03-17 09:38 UTC, taoyuanyuan approved these changes
LGTM

2021-03-17 09:47 UTC, zonghaishang requested changes

2021-03-17 09:47 UTC, zonghaishang commented on pkg/wasm/runtime/wasmer/instance.go
> +// +build Wasmer
change Wasmer to wasmer

2021-03-17 09:47 UTC, zonghaishang commented on pkg/wasm/runtime/wasmer/types.go
> +// +build Wasmer
change Wasmer to wasmer

2021-03-17 09:47 UTC, zonghaishang commented on pkg/wasm/runtime/wasmer/module.go
> +// +build Wasmer
change Wasmer to wasmer

2021-03-17 09:47 UTC, zonghaishang commented on pkg/wasm/runtime/wasmer/vm.go
> +// +build Wasmer
change Wasmer to wasmer

2021-03-17 09:48 UTC, zonghaishang commented
https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool

2021-03-17 10:44 UTC, taoyuanyuan approved these changes
LGTM

2021-03-18 01:49 UTC, wangfakang approved these changes
LGTM.

2021-03-18 02:41 UTC, merged