Modify NewSubsetLoadBalancer structure parameters to interface
mosn/mosn pull request #1634
Opened 2021-04-21 09:10 UTC by alpha-baby

### Issues associated with this PR

把参数从结构体改成接口，感觉这样更优雅点

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases. And you need to show the UT result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result.

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

2021-04-22 01:41 UTC, taoyuanyuan approved these changes
THX， LGTM

2021-05-12 08:54 UTC, alpha-baby commented
@taoyuanyuan review again, thx

2021-05-12 09:38 UTC, taoyuanyuan commented
@nejisama cc

2021-05-14 03:20 UTC, nejisama commented
新增一个接口CreateSubset 的目的就是为了代码重构？没有实际需求吗

2021-05-14 03:29 UTC, nejisama requested changes

2021-05-14 03:29 UTC, nejisama commented on pkg/types/upstream.go
> +	CreateSubset(predicate HostPredicate) HostSet
CreateSubset的逻辑这样修改以后，是可以被任意修改的，可能会导致subset的逻辑变化，如果没有明确的需求就不要新增这个接口了

2021-05-14 03:34 UTC, alpha-baby commented on pkg/types/upstream.go
> +	CreateSubset(predicate HostPredicate) HostSet
增加这个接口是因为 可以废弃 subHostSet 结构体，

2021-05-14 03:44 UTC, nejisama commented on pkg/types/upstream.go
> +	CreateSubset(predicate HostPredicate) HostSet
感觉是为了重构而重构，没有什么实际的价值

2021-05-14 03:45 UTC, nejisama commented on pkg/types/upstream.go
> +	CreateSubset(predicate HostPredicate) HostSet
还会导致以前的一些代码不兼容的问题

2021-05-14 03:48 UTC, nejisama commented on pkg/types/upstream.go
> +	CreateSubset(predicate HostPredicate) HostSet
CreateSubset 这个函数目前看来应该是没有别的实现的需求的，额外的实现可能还会导致逻辑的问题，为了废弃subHostSet 可以考虑别的办法来做，再想想看把

2021-05-14 05:49 UTC, alpha-baby commented on pkg/upstream/cluster/subset_loadbalancer.go
> +					subHostset := sslb.hostSet.CreateSubset(func(host types.Host) bool {
增加了 CreateSubset  方法其实是在这里需要调用，不然我也不会在 types.Host中增加一个方法
@nejisama

2021-05-14 06:43 UTC, nejisama commented on pkg/upstream/cluster/subset_loadbalancer.go
> +					subHostset := sslb.hostSet.CreateSubset(func(host types.Host) bool {
你这样修改以后 相当于支持subset的逻辑可以被替换掉，目前的设计下这样的逻辑应该是会出问题的。
只看到了增加方法可以解决这个问题，没有看到其他可能潜在的问题，这样的改动是不行的

2021-05-14 07:23 UTC, nejisama commented
比如可以把CreateSubset 从hostset中删除，做成一个独立的函数，入参增加一个types.HostSet ，保持hostset的接口定义不变，看下是否可行 @alpha-baby

2021-05-14 11:11 UTC, nejisama approved these changes

2021-05-14 15:01 UTC, taoyuanyuan approved these changes

2021-05-14 15:02 UTC, merged