MOSN支持go plugin加载协议转化插件，并支持动态选择协议转换插件
mosn/mosn pull request #1842
Opened 2021-11-17 02:52 UTC by Tanc010

# Issues associated with this PR

目前mosn通过增加transcoder的stream filter并且指定type就可以实现协议转换。但是，一个listener下只能实现一种协议转换，也就是，只能A协议转B协议，不能同时存在A转B、A转C、A转D，并通过请求参数信息灵活的选择要转的协议。

此外，可以将协议转换做成go plugin插件，用户单独编译即可。

# Solutions

## 配置

### config.json

1、保留type，兼容之前协议转换方式

2、增加rules、go_plugin_config

3、go_plugin_config配置多个协议转换插件

4、rules配置协议转换插件匹配规则

5、type和[rules、go_plugin_config]至少有一个

```json
{
    "servers":[
        {
            "listeners":[
                {
                    "stream_filters":[
                        {
                            "type":"transcoder",
                            "config":{
                                "type":"http2bolt_simple",
                                "rules":[
                                    {
                                        "macther_config":{
                                            "variables":[

                                            ]
                                        },
                                        "rule_info":{
                                            "upstream_sub_protocol":"bolt",
                                            "upstream_protocol":"X",
                                            "config":{

                                            },
                                            "description":""
                                        }
                                    }
                                ],
                                "go_plugin_config":{
                                    "transcoders":[
                                        {
                                            "so_path":"/Users/xxx/go/src/mosn.io/mosn/configs/dev/http2bolt.so",
                                            "src_protocol":"Http1",
                                            "dst_protocol":"bolt"
                                        }
                                    ]
                                }
                            }
                        }
                    ]
                }
            ]
        }
    ],
    "cluster_manager":{

    },
    "tracing":{

    }
}
```

### macther_config

```json
{
  "headers": [],
  "variables": []
}
```

- header匹配，表示一组请求需要匹配的 header。请求需要满足配置中所有的 Header 配置条件才算匹配成功
- variable匹配，表示一组请求需要匹配的 variable。

headers和variables同时配置时，只有variables生效。

#### header

```json
{
  "name":"",
  "value":"",
  "regex":""
}
```

- name，表示 header 的 key。
- value，表示 header 对应 key 的 value。

- regex，bool 类型，如果为 true，表示 value 支持按照正则表达式的方式进行匹配。

#### variable

```json
{
  "name":"",
  "value":"",
  "regex":"",
  "operator":"",
}
```

- name，表示 variable 的 key。
- value，表示 variable 对应 key 的 value。

- regex，bool 类型，如果为 true，表示 value 支持按照正则表达式的方式进行匹配。
- operator，操作类型，支持 && 和 ||

### rule_info

```json
{
    "upstream_sub_protocol":"bolt",
    "upstream_protocol":"X",
    "config":{

    },
    "description":""
}
```

协议转换规则元信息

- upstream_protocol，目标协议类型，包含X、HTTP1、HTTP2等
- upstream_sub_protocol，目标协议，包含bolt、dubbo、springcloud等

- config， 协议转换插件配置。map结构
- description，描述

### transcoders

协议转换插件配置

- src_protocol 原协议（转换前协议）
- dst_protocol 目标协议 （转换后协议）

- so_path 协议转换插件so文件

## 代码

### 执行协议转换插件

```go
func (f *transcodeFilter) OnReceive(ctx context.Context, headers types.HeaderMap, buf types.IoBuffer, trailers types.HeaderMap) api.StreamFilterStatus {

	var outHeaders, outTrailers types.HeaderMap
	var outBuf types.IoBuffer
	var err error
	var transcoder Transcoder

    //匹配协议转换规则
	if ruleInfo, ok := f.Matches(ctx, headers); ok {//匹配到协议转换规则
		srcPro := mosnctx.Get(ctx, types.ContextKeyDownStreamProtocol).(api.ProtocolName)
		dstPro := ruleInfo.UpstreamSubProtocol
		listenerName := mosnctx.Get(ctx, types.ContextKeyListenerName).(string)
		pluginName := listenerName + "_" + string(srcPro) + "_" + dstPro

		//select transcoder
        //获取协议转换插件
		transcoder = GetTranscoder(pluginName)
		if transcoder == nil {
			log.Proxy.Errorf(ctx, "[stream filter][transcoder] cloud not found transcoder")
			return api.StreamFilterContinue
		}
		// check accept
        //执行协议转换插件Accept
		if !transcoder.Accept(ctx, headers, buf, trailers) {
			return api.StreamFilterContinue
		}

		//set sub protocol
		mosnctx.WithValue(ctx, types.ContextSubProtocol, dstPro)
		//set upstream protocol
		mosnctx.WithValue(ctx, types.ContextKeyUpStreamProtocol, ruleInfo.UpstreamProtocol)

	} else if f.transcoder != nil {匹配不到协议转换规则，则走原有的逻辑
		// check accept
		if !f.transcoder.Accept(ctx, headers, buf, trailers) {
			return api.StreamFilterContinue
		}

		// for response check
		f.needTranscode = true

		if log.Proxy.GetLogLevel() >= log.DEBUG {
			log.Proxy.Debugf(ctx, "[stream filter][transcoder] receive request: %+v", headers)
		}

		transcoder = f.transcoder
	}

	if route := f.receiveHandler.Route(); route != nil {
		// TODO: makes ReadPerRouteConfig as the StreamReceiverFilter's function
		f.readPerRouteConfig(ctx, route.RouteRule().PerFilterConfig())
	}
	// do transcoding
    //转换request
	outHeaders, outBuf, outTrailers, err = transcoder.TranscodingRequest(ctx, headers, buf, trailers)

	if err != nil {
		log.Proxy.Errorf(ctx, "[stream filter][transcoder] transcoder request failed: %v", err)
		f.receiveHandler.RequestInfo().SetResponseFlag(RequestTranscodeFail)
		f.receiveHandler.SendHijackReply(http.StatusBadRequest, headers)
		return api.StreamFilterStop
	}

	f.receiveHandler.SetRequestHeaders(outHeaders)
	f.receiveHandler.SetRequestData(outBuf)
	f.receiveHandler.SetRequestTrailers(outTrailers)
	f.receiveHandler.SetConvert(false)
	return api.StreamFilterContinue
}
```

### 加载协议插件

```go
type TranscoderGoPlugin struct {
	SrcPro string `json:"src_protocol,omitempty"`
	DstPro string `json:"dst_protocol,omitempty"`
	SoPath string `json:"so_path,omitempty"`
}

//加载so
func (t *TranscoderGoPlugin) CreateTranscoder(listenerName string) {

	if t.SrcPro == "" || t.DstPro == "" || t.SoPath == "" {
		log.DefaultLogger.Errorf("[stream filter][transcoder] config could not be found, srcPro: %s,"+
			" dsrPro: %s, soPath: %s", t.SrcPro, t.DstPro, t.SoPath)
		return
	}

	name := listenerName + "_" + t.SrcPro + "_" + t.DstPro

	if GetTranscoder(name) != nil {
		return
	}

	p, err := goplugin.Open(t.SoPath) //根据路径加载***.so文件
	if err != nil {
		log.DefaultLogger.Errorf("[stream filter][transcoder] so file could not be load, soPath: %s, err: %v", t.SoPath, err)
		return
	}

	sym, err := p.Lookup("LoadTranscoder")
	if err != nil {
		log.DefaultLogger.Errorf("[stream filter][transcoder] so file look up error, soPath: %s, err: %v", t.SoPath, err)
		return
	}

	loadFunc := sym.(func() Transcoder)
	transcoderSo := loadFunc() //执行函数，该函数其实是初始化transcoder

	MustRegister(name, transcoderSo)
}

//创建filter
func newTranscodeFilter(ctx context.Context, cfg *config) *transcodeFilter {
	if log.Proxy.GetLogLevel() >= log.DEBUG {
		log.Proxy.Debugf(ctx, "[stream filter][transcoder] create transcoder filter with config: %v", cfg)
	}

	transcoder := GetTranscoder(cfg.Type).(Transcoder)
    
    //初始化协议转换插件
	if !initTranscodePlugin(ctx, cfg.GoPluginConfig) && transcoder == nil {
		log.Proxy.Errorf(ctx, "[stream filter][transcoder] create failed, no such transcoder type: %s", cfg.Type)
		return nil
	}

	return &transcodeFilter{
		ctx:        ctx,
		cfg:        cfg,
		transcoder: transcoder,
	}
}

//初始化协议转换插件
func initTranscodePlugin(ctx context.Context, cfg *transcodeGoPluginConfig) bool {
	if cfg == nil {
		return false
	}
	listenerName := mosnctx.Get(ctx, types.ContextKeyListenerName).(string)
	for _, transcoder := range cfg.Transcoders {
        //加载so
		transcoder.CreateTranscoder(listenerName)
	}

	return true
}
```

### 匹配规则和加载协议转换规则

```go
func (f *transcodeFilter) Matches(ctx context.Context, headers types.HeaderMap) (*rules.RuleInfo, bool) {

	listenerName := mosnctx.Get(ctx, types.ContextKeyListenerName).(string)
    //从远程配置中心加载协议转换规则
	transferRuleConfigs, result := rules.GetInstanceTransferRuleManger().GetTransferRule(listenerName)
	if !result {
        //从config中获取协议转换规则
		transferRuleConfigs = [...]

2021-11-17 13:48 UTC, zonghaishang requested changes

2021-11-17 13:48 UTC, zonghaishang commented on pkg/filter/stream/transcoder/factory.go
> +	if transcoderFactory[typ] != nil {
这个未来支持重复注册是否有问题？比如动态替换。

2021-11-17 13:48 UTC, zonghaishang commented on pkg/filter/stream/transcoder/factory.go
> +	log.DefaultLogger.Infof("[stream filter][transcoder][factory]GetTranscoder, typ %s, transcoderFactory %+v", typ, transcoderFactory)
改成DEBUG级别日志

2021-11-17 13:48 UTC, zonghaishang commented on pkg/filter/stream/transcoder/filter.go
> +	log.DefaultLogger.Infof("[stream filter][transcoder] result %s, transferRuleConfigs %+v", result, transferRuleConfigs)
每次match info日志太多，改成debug级别

2021-11-18 02:44 UTC, nejisama commented on examples/codes/transcodes_with_goplugin_example/client_config.json
> +                      "desc":"5.2.1 互金->T24已迁移服务 ws->mosn -> mosn-> sk"
这些改一下吧，改成什么test一类的

2021-11-18 02:47 UTC, nejisama commented on go.mod
> +	mosn.io/api v0.0.0-20210714065837-5b4c2d66e70c => github.com/zonghaishang/api v0.0.0-20211111063821-9f6ab4c6e576
replace要去掉

2021-11-18 02:48 UTC, nejisama commented on examples/codes/transcodes_with_goplugin_example/server_config.json
> +}
example 还需要配文字说明 怎么运行，什么样的结果。光一堆代码和配置不行

2021-11-18 02:50 UTC, nejisama commented on pkg/filter/stream/transcoder/factory.go
> +	api.RegisterStream("transcoder", createFilterChainFactory)
如果仅是不希望依赖config/v2，这里可以把transcoder 的常量定义放到transcoder的filter下

2021-11-18 02:51 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +	if !initTranscodePlugin(ctx, cfg.GoPluginConfig) && transcoder == nil {
这里用 and 是不是不太对，应该是 or 吧

2021-11-18 02:52 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +	listenerName := mosnctx.Get(ctx, types.ContextKeyListenerName).(string)
获取Listener的配置不应该用这种方式，可以参考filter/network/grpc/factory.go 中的Init 实现

2021-11-18 02:54 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +	if transcodeCfg, ok := cfg["transcoder"]; ok {
和注册一样，统一使用常量

2021-11-18 02:59 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
>  	if route := f.receiveHandler.Route(); route != nil {
这个应该在配置解析之前生效，否则逻辑就不对了。

2021-11-18 03:02 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +func (f *transcodeFilter) Matches(ctx context.Context, headers types.HeaderMap) (*rules.RuleInfo, bool) {
缺少必要的单元测试

2021-11-18 03:03 UTC, nejisama commented on pkg/filter/stream/transcoder/plugin.go
> +	p, err := goplugin.Open(t.SoPath) //根据路径加载***.so文件
去掉中文注释

2021-11-18 03:03 UTC, nejisama commented on pkg/filter/stream/transcoder/plugin.go
> +	transcoderSo := loadFunc() //执行函数，该函数其实是初始化transcoder
去掉中文注释

2021-11-18 03:12 UTC, nejisama commented on pkg/filter/stream/transcoder/rules/matcher.go
> +func (tf *TransferRuleConfig) Matches(ctx context.Context, headers types.HeaderMap) (*RuleInfo, bool) {
同样补充单元测试，验证各种匹配规则是否符合预期

2021-11-18 03:12 UTC, nejisama commented on pkg/filter/stream/transcoder/rules/matcher.go
> +func (m *simpleMatcher) Matches(ctx context.Context, headers types.HeaderMap, config *MatcherConfig) bool {
这个似乎没有什么意义？

2021-11-18 03:13 UTC, nejisama commented on pkg/filter/stream/transcoder/rules/matcher_factory.go
> +var transferMatcher TransferMatcher
这个全局变量的作用是什么？

2021-11-18 03:14 UTC, nejisama commented on pkg/filter/stream/transcoder/rules/matcher_factory.go
> +var transferMatcher TransferMatcher
这里看上去是想做成可扩展的规则，然后默认的TransferRuleConfig只是其中一种。那么这里似乎不应该用全局变量，而是每个配置可以获取不同的匹配规则

2021-11-18 03:15 UTC, nejisama commented on pkg/filter/stream/transcoder/rules/matcher_factory.go
> +var transferMatcher TransferMatcher
感觉是对TransferMatcher 这个接口的用处没有考虑清楚，建议梳理一下，后面的RuleManager看上去是做这个事的，但是又固定返回其中一个实现

2021-11-18 07:19 UTC, Tanc010 commented on pkg/filter/stream/transcoder/filter.go
> +	if !initTranscodePlugin(ctx, cfg.GoPluginConfig) && transcoder == nil {
是and，这里我加一下注释

2021-11-18 07:26 UTC, Tanc010 commented on examples/codes/transcodes_with_goplugin_example/server_config.json
> +}
example我先去掉，后续再补充详细的使用指南

2021-11-18 07:28 UTC, Tanc010 commented on pkg/filter/stream/transcoder/factory.go
> +	if transcoderFactory[typ] != nil {
动态替换也是应该要重启mosn

2021-11-18 09:58 UTC, Tanc010 commented on pkg/filter/stream/transcoder/filter.go
> +	listenerName := mosnctx.Get(ctx, types.ContextKeyListenerName).(string)
只是获取listener名，这样的改动范围只在streamfilter内。

2021-11-18 11:12 UTC, Tanc010 commented on pkg/filter/stream/transcoder/filter.go
>  	if route := f.receiveHandler.Route(); route != nil {
这个配置是动态的，应该是为下次请求使用

2021-11-18 11:39 UTC, taoyuanyuan commented on pkg/types/context.go
> +	ContextKeyTranscoderConfig
这个是框架的变量，模块的不能放这儿哟

2021-11-18 11:43 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +	listenerName := mosnctx.Get(ctx, types.ContextKeyListenerName).(string)
本来Init也是在stream filter范围内的啊

2021-11-18 11:46 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
>  	if route := f.receiveHandler.Route(); route != nil {
这里逻辑不太对。这个函数的意思是如果路由级别有Filter相同的配置，以路由级别的配置为准。但是现在这里配置都解析完了，再替换配置已经没有意义了。如果不准备实现这个逻辑，就把这一段逻辑去掉。实现了这样的逻辑应该是不对的

2021-11-18 12:31 UTC, nejisama commented on go.mod
> -replace github.com/envoyproxy/go-control-plane => github.com/envoyproxy/go-control-plane v0.9.4
这个replace 需要保留的

2021-11-18 13:01 UTC, Tanc010 commented on pkg/types/context.go
> +	ContextKeyTranscoderConfig
我想在context里加配置，如果这里不给加会导致开发者没法在context加配置了，扩展性不好。
我觉得可以加一个ContextKeyExtensionConfig

2021-11-18 13:10 UTC, taoyuanyuan commented on pkg/types/context.go
> +	ContextKeyTranscoderConfig
你看一下变量怎么用的
https://github.com/mosn/mosn/blob/d3403fb5d48f43f637547190a46ab29649a8533d/pkg/filter/stream/dubbo/var.go#L32

2021-11-18 14:08 UTC, Tanc010 commented on pkg/filter/stream/transcoder/filter.go
> +	listenerName := mosnctx.Get(ctx, types.ContextKeyListenerName).(string)
Init是network filter才有，我的意思是需要定义方法给框架层调。也可能是没有get到怎么改，应该怎么改？

2021-11-18 14:08 UTC, Tanc010 commented on pkg/filter/stream/transcoder/filter.go
>  	if route := f.receiveHandler.Route(); route != nil {
这个是之前就有的逻辑，我把这块注掉吧

2021-11-18 14:10 UTC, Tanc010 commented on pkg/types/context.go
> +	ContextKeyTranscoderConfig
我想存到context里

2021-11-18 14:46 UTC, taoyuanyuan commented on pkg/types/context.go
> +	ContextKeyTranscoderConfig
为什么？

2021-11-19 02:34 UTC, Tanc010 commented on pkg/types/context.go
> +	ContextKeyTranscoderConfig
我调整一下

2021-11-19 10:24 UTC, Tanc010 commented on pkg/filter/stream/transcoder/filter.go
> +	if !initTranscodePlugin(ctx, cfg.GoPluginConfig) && transcoder == nil {
done

2021-11-19 10:27 UTC, Tanc010 commented on pkg/filter/stream/transcoder/rules/matcher.go
> +func (m *simpleMatcher) Matches(ctx context.Context, headers types.HeaderMap, config *MatcherConfig) bool {
已经修改和加了注释。这个就是提供一个简单的匹配规则的方法，后续再提供比较复杂的实现

2021-11-19 10:45 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +	listenerName := mosnctx.Get(ctx, types.ContextKeyListenerName).(string)
那改成创建时获取一次吧，不要每次都重复获取。 filter是有状态的。 这个函数也可以变成filter或者factory里的成员函数

2021-11-19 10:46 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +	listenerName := mosnctx.Get(ctx, types.ContextKeyListenerName).(string)
因为我看你后面很多地方都在用这个

2021-11-19 10:47 UTC, nejisama commented on pkg/filter/stream/transcoder/rules/matcher.go
> +func (m *simpleMatcher) Matches(ctx context.Context, headers types.HeaderMap, config *MatcherConfig) bool {
没搞懂，这个TransferMatcher 和 后面TransferRuleManager 管理的内容有什么关系，为什么要分两个全局变量来注册。 这里是不是来一点设计文档会比较好理解

2021-11-19 10:48 UTC, nejisama commented on pkg/filter/stream/transcoder/rules/matcher_factory.go
> +		panic("target stream macther already exists: " + typ)
这种panic 没什么意义，如果想直接异常，用log的Fatal方法，panic不一定挂得掉

2021-11-21 13:15 UTC, Tanc010 commented on pkg/filter/stream/transcoder/filter.go
> +	listenerName := mosnctx.Get(ctx, types.ContextKeyListenerName).(string)
已修改

2021-11-21 13:16 UTC, Tanc010 commented on pkg/filter/stream/transcoder/rules/matcher.go
> +func (m *simpleMatcher) Matches(ctx context.Context, headers types.HeaderMap, config *MatcherConfig) bool {
![20211121210447](https://user-images.githubusercontent.com/94040830/142763369-993c9736-50ce-436a-a85c-1563c15a6c88.jpg)

2021-11-25 07:34 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +	listenerName := mosnctx.Get(ctx, types.ContextKeyListenerName).(string)
listener name 应该初始化就获取了

2021-11-25 07:35 UTC, nejisama commented on pkg/filter/stream/transcoder/rules/matcher.go
> +func (m *simpleMatcher) Matches(ctx context.Context, headers types.HeaderMap, config *MatcherConfig) bool {
还是没看懂。根据你的配置设计，不应该是每个Listener的配置有一组自己的配置规则，然后会根据规则来选择用哪个协议转换吗？为什么搞那么多全局的变量

2021-11-25 07:43 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +		transferRuleConfigs = f.cfg.Rules
这里的逻辑看上去是想用一个全局的Rule 覆盖Listener级别配置的Rule，这个TransferRuleManger实际上是做了一个全局的MAP来保存每个Listener的配置？这样的设计有什么必要？是想做动态配置更新搞成这样的？

2021-11-25 08:22 UTC, nejisama commented
我从头到尾重新看了下，我感觉目前的实现中很多地方没有想清楚，设计的不够清晰，不利于后续的维护。
从设计目标来看，应该包含两个点
1.  支持通过So的方式加载具体的协议转换实现，比如http1 -> bolt 的转换能力，通过 http2bolt.so进行实现
2. 支持一个transcoder filter 根据不同的请求条件，选择不同的协议转换的能力

按照这两个需求，来看现在的实现

1. 协议转换的实现So，每个Filter配置可以根据ListenerName独立加载，也就是通用的协议转换可以用不同的so实现，用于不同的listener中，这个是否有必要？
 -> 即便是需要Listener级别的配置，也应该在创建Factory的时候决定，不是在每次NewFilter的时候决定

2. Rules配置，应该是按照配置顺序优先级，根据MatchConfig的条件进行匹配，如果匹配成功，就会根据Rule配置中的RuleInfo选择协议转换的实现，进行协议转换。MatchConfig支持多种匹配的实现，所以又实现了一个MatcherType来进行选择; 同时又设计了MatcherType的扩展，可以自定义Match能力的实现。
-> 但是实际上MatchConfig本身只能配置Header和Variables，这里的扩展感觉能扩展的也有限？ 另外MatchType 也不应该独立出去配置，应该和MatchConfig在一起

3. TransferRuleManager 用一个全局变量保存所有的Transcoder Listener的配置，并且优先级高于原始配置的实现，看上去是为了做动态更新进行的实现， 如果有这个需求，是否可以考虑直接就基于MOSN的LDS实现就可以了。还是有别的需求？

2021-11-29 06:20 UTC, YIDWang approved these changes

2021-11-29 06:48 UTC, nejisama commented on pkg/filter/stream/transcoder/config.go
插件统一处理

2021-11-29 06:50 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +	v2 "mosn.io/mosn/pkg/config/v2"
fmt style

2021-11-29 06:50 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +			ruleInfo.Type = string(srcPro) + "_" + dstPro
rulInfo 的结构体把这种调用屏蔽掉

2021-11-29 06:52 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +		//set sub protocol
> 

应该不需要这个判断，在目前的设计看来，如果是HTTP SUB应该是和非SUB是一样的

2021-11-29 06:53 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> -	if !f.needTranscode {
这个判断感觉不能忽视，如果OnReceive没有转换过，那么Append 应该就不执行转换了

2021-11-29 06:54 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +
> 

没理解说的是什么内容

2021-11-29 07:06 UTC, Tanc010 commented on pkg/filter/stream/transcoder/filter.go
> -	if !f.needTranscode {
如果OnReceive没有转，Append 也不会转。都是通过TransCoderMatches来判断。

2021-11-29 07:26 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> -	if !f.needTranscode {
不对啊，这个Match不是框架实现的啊

2021-11-29 07:27 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> -	if !f.needTranscode {
最简单的就是，比如Match的规则是Header里包含特定的key:value 就匹配成功。请求里没有这个key:value，不代表响应也一定没有，你这时候去做协议转换，结果肯定是错的啊。

2021-11-30 03:22 UTC, nejisama commented on pkg/filter/stream/transcoder/filter.go
> +	"mosn.io/api/extensions/transcoder"
import的风格不对，调整一下

2021-11-30 07:12 UTC, nejisama commented on pkg/filter/stream/transcoder/plugin.go
> +	json.Unmarshal(data, cfg)
err check

2021-11-30 07:12 UTC, nejisama commented on pkg/filter/stream/transcoder/matcher/config.go
> +	Config              map[string]interface{} `json:"config,omitempty"`
使用这个Config的接口似乎没有保留

2021-11-30 07:12 UTC, nejisama commented on pkg/filter/stream/transcoder/simplematcher/simple_matcher.go
> +type SimpleRuleMatcher struct {
除了Simple 永远返回true的实现，还应该再加一个简单的要读取配置的实现吧，不然看代码都不太明白这一块到底要怎么搞

2021-11-30 08:52 UTC, YIDWang approved these changes

2021-12-01 10:10 UTC, nejisama approved these changes

2021-12-01 10:34 UTC, taoyuanyuan approved these changes

2021-12-02 02:58 UTC, merged