[feature] support record health check log
mosn/mosn pull request #2096
Opened 2022-08-02 10:57 UTC by dengqian

2022-08-03 09:30 UTC, nejisama commented on pkg/upstream/healthcheck/healthchecker.go
> +func (hc *healthChecker) runCallbacks(host types.Host, changed bool, isHealthy bool, info string) {
这里callback新增一个info 感觉比较难以理解 是不是可以考虑单独搞出来呢

2022-08-03 09:32 UTC, nejisama commented on pkg/upstream/healthcheck/healthchecklog.go
> +	if l.logger != nil {
logger 不存在可以直接return了 否则拼接的buf也没用 & 没人回收

2022-08-05 07:02 UTC, nejisama commented on pkg/upstream/healthcheck/healthchecker.go
> +func (hc *healthChecker) runCallbacks(host types.Host, changed bool, isHealthy bool, info string) {
我建议是不要修改callback函数，可以考虑单独搞一个日志类的扩展

2022-08-05 07:02 UTC, nejisama requested changes
我建议是不要修改callback函数，可以考虑单独搞一个日志类的扩展

2022-08-29 12:07 UTC, dengqian commented on pkg/upstream/healthcheck/healthchecker.go
> +func (hc *healthChecker) runCallbacks(host types.Host, changed bool, isHealthy bool, info string) {
> 这里callback新增一个info 感觉比较难以理解 是不是可以考虑单独搞出来呢

callback也可能需要本次check的详细信息，感觉log应当属于callback的一种，不是很有拆分的必要

2022-09-02 02:16 UTC, nejisama commented on pkg/upstream/healthcheck/healthchecker.go
> +func (hc *healthChecker) runCallbacks(host types.Host, changed bool, isHealthy bool, info string) {
callback 已经有很多地方在使用了，这样改其他使用的地方都需要做兼容处理，而大部分都没有必要。
check的内容目前看设计上只是一个描述的字符串，需要用到的地方应该不多吧

2022-12-13 10:12 UTC, nejisama commented on pkg/upstream/healthcheck/healthchecklog.go
> +	s := fmt.Sprintf(defaultHealthCheckFormat, time.Now().Unix(), host.AddressString(), boolToInt(host.Health()),
这里建议不要用Sprintf来拼接，可以参考tracelog里的做法pkg/trace/sofa/span.go  直接拆分来write

2022-12-13 10:12 UTC, nejisama commented on pkg/upstream/healthcheck/healthchecklog_test.go
> +func TestHealthCheckLog(t *testing.T) {
如果重复跑测试会有问题吧，应该先尝试删除旧文件，确保每次都新的

2022-12-14 06:39 UTC, nejisama approved these changes

2022-12-14 06:57 UTC, taoyuanyuan approved these changes

2022-12-14 06:57 UTC, merged